// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.0
// source: extensions/filters/v1/http/ext_authz/ext_authz.proto

package ext_authzv1

import (
	rbac "github.com/kdubbo/xds-api/extensions/filters/v1/http/rbac"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	durationpb "google.golang.org/protobuf/types/known/durationpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ExtAuthz_Protocol int32

const (
	ExtAuthz_HTTP ExtAuthz_Protocol = 0
	ExtAuthz_GRPC ExtAuthz_Protocol = 1
)

// Enum value maps for ExtAuthz_Protocol.
var (
	ExtAuthz_Protocol_name = map[int32]string{
		0: "HTTP",
		1: "GRPC",
	}
	ExtAuthz_Protocol_value = map[string]int32{
		"HTTP": 0,
		"GRPC": 1,
	}
)

func (x ExtAuthz_Protocol) Enum() *ExtAuthz_Protocol {
	p := new(ExtAuthz_Protocol)
	*p = x
	return p
}

func (x ExtAuthz_Protocol) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ExtAuthz_Protocol) Descriptor() protoreflect.EnumDescriptor {
	return file_extensions_filters_v1_http_ext_authz_ext_authz_proto_enumTypes[0].Descriptor()
}

func (ExtAuthz_Protocol) Type() protoreflect.EnumType {
	return &file_extensions_filters_v1_http_ext_authz_ext_authz_proto_enumTypes[0]
}

func (x ExtAuthz_Protocol) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ExtAuthz_Protocol.Descriptor instead.
func (ExtAuthz_Protocol) EnumDescriptor() ([]byte, []int) {
	return file_extensions_filters_v1_http_ext_authz_ext_authz_proto_rawDescGZIP(), []int{0, 0}
}

type ExtAuthz struct {
	state                        protoimpl.MessageState `protogen:"open.v1"`
	Provider                     string                 `protobuf:"bytes,1,opt,name=provider,proto3" json:"provider,omitempty"`
	Protocol                     ExtAuthz_Protocol      `protobuf:"varint,2,opt,name=protocol,proto3,enum=extensions.filters.http.ext_authz.v1.ExtAuthz_Protocol" json:"protocol,omitempty"`
	Service                      string                 `protobuf:"bytes,3,opt,name=service,proto3" json:"service,omitempty"`
	Port                         uint32                 `protobuf:"varint,4,opt,name=port,proto3" json:"port,omitempty"`
	PathPrefix                   string                 `protobuf:"bytes,5,opt,name=path_prefix,json=pathPrefix,proto3" json:"path_prefix,omitempty"`
	IncludeRequestHeadersInCheck []string               `protobuf:"bytes,6,rep,name=include_request_headers_in_check,json=includeRequestHeadersInCheck,proto3" json:"include_request_headers_in_check,omitempty"`
	HeadersToUpstreamOnAllow     []string               `protobuf:"bytes,7,rep,name=headers_to_upstream_on_allow,json=headersToUpstreamOnAllow,proto3" json:"headers_to_upstream_on_allow,omitempty"`
	HeadersToDownstreamOnDeny    []string               `protobuf:"bytes,8,rep,name=headers_to_downstream_on_deny,json=headersToDownstreamOnDeny,proto3" json:"headers_to_downstream_on_deny,omitempty"`
	Timeout                      *durationpb.Duration   `protobuf:"bytes,9,opt,name=timeout,proto3" json:"timeout,omitempty"`
	FailOpen                     bool                   `protobuf:"varint,10,opt,name=fail_open,json=failOpen,proto3" json:"fail_open,omitempty"`
	Shadow                       bool                   `protobuf:"varint,11,opt,name=shadow,proto3" json:"shadow,omitempty"`
	Rules                        []*rbac.Rule           `protobuf:"bytes,12,rep,name=rules,proto3" json:"rules,omitempty"`
	unknownFields                protoimpl.UnknownFields
	sizeCache                    protoimpl.SizeCache
}

func (x *ExtAuthz) Reset() {
	*x = ExtAuthz{}
	mi := &file_extensions_filters_v1_http_ext_authz_ext_authz_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExtAuthz) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExtAuthz) ProtoMessage() {}

func (x *ExtAuthz) ProtoReflect() protoreflect.Message {
	mi := &file_extensions_filters_v1_http_ext_authz_ext_authz_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExtAuthz.ProtoReflect.Descriptor instead.
func (*ExtAuthz) Descriptor() ([]byte, []int) {
	return file_extensions_filters_v1_http_ext_authz_ext_authz_proto_rawDescGZIP(), []int{0}
}

func (x *ExtAuthz) GetProvider() string {
	if x != nil {
		return x.Provider
	}
	return ""
}

func (x *ExtAuthz) GetProtocol() ExtAuthz_Protocol {
	if x != nil {
		return x.Protocol
	}
	return ExtAuthz_HTTP
}

func (x *ExtAuthz) GetService() string {
	if x != nil {
		return x.Service
	}
	return ""
}

func (x *ExtAuthz) GetPort() uint32 {
	if x != nil {
		return x.Port
	}
	return 0
}

func (x *ExtAuthz) GetPathPrefix() string {
	if x != nil {
		return x.PathPrefix
	}
	return ""
}

func (x *ExtAuthz) GetIncludeRequestHeadersInCheck() []string {
	if x != nil {
		return x.IncludeRequestHeadersInCheck
	}
	return nil
}

func (x *ExtAuthz) GetHeadersToUpstreamOnAllow() []string {
	if x != nil {
		return x.HeadersToUpstreamOnAllow
	}
	return nil
}

func (x *ExtAuthz) GetHeadersToDownstreamOnDeny() []string {
	if x != nil {
		return x.HeadersToDownstreamOnDeny
	}
	return nil
}

func (x *ExtAuthz) GetTimeout() *durationpb.Duration {
	if x != nil {
		return x.Timeout
	}
	return nil
}

func (x *ExtAuthz) GetFailOpen() bool {
	if x != nil {
		return x.FailOpen
	}
	return false
}

func (x *ExtAuthz) GetShadow() bool {
	if x != nil {
		return x.Shadow
	}
	return false
}

func (x *ExtAuthz) GetRules() []*rbac.Rule {
	if x != nil {
		return x.Rules
	}
	return nil
}

var File_extensions_filters_v1_http_ext_authz_ext_authz_proto protoreflect.FileDescriptor

const file_extensions_filters_v1_http_ext_authz_ext_authz_proto_rawDesc = "" +
	"\n" +
	"4extensions/filters/v1/http/ext_authz/ext_authz.proto\x12$extensions.filters.http.ext_authz.v1\x1a\x1egoogle/protobuf/duration.proto\x1a*extensions/filters/v1/http/rbac/rbac.proto\"\xdb\x04\n" +
	"\bExtAuthz\x12\x1a\n" +
	"\bprovider\x18\x01 \x01(\tR\bprovider\x12S\n" +
	"\bprotocol\x18\x02 \x01(\x0e27.extensions.filters.http.ext_authz.v1.ExtAuthz.ProtocolR\bprotocol\x12\x18\n" +
	"\aservice\x18\x03 \x01(\tR\aservice\x12\x12\n" +
	"\x04port\x18\x04 \x01(\rR\x04port\x12\x1f\n" +
	"\vpath_prefix\x18\x05 \x01(\tR\n" +
	"pathPrefix\x12F\n" +
	" include_request_headers_in_check\x18\x06 \x03(\tR\x1cincludeRequestHeadersInCheck\x12>\n" +
	"\x1cheaders_to_upstream_on_allow\x18\a \x03(\tR\x18headersToUpstreamOnAllow\x12@\n" +
	"\x1dheaders_to_downstream_on_deny\x18\b \x03(\tR\x19headersToDownstreamOnDeny\x123\n" +
	"\atimeout\x18\t \x01(\v2\x19.google.protobuf.DurationR\atimeout\x12\x1b\n" +
	"\tfail_open\x18\n" +
	" \x01(\bR\bfailOpen\x12\x16\n" +
	"\x06shadow\x18\v \x01(\bR\x06shadow\x12;\n" +
	"\x05rules\x18\f \x03(\v2%.extensions.filters.http.rbac.v1.RuleR\x05rules\"\x1e\n" +
	"\bProtocol\x12\b\n" +
	"\x04HTTP\x10\x00\x12\b\n" +
	"\x04GRPC\x10\x01BLZJgithub.com/kdubbo/xds-api/extensions/filters/v1/http/ext_authz;ext_authzv1b\x06proto3"

var (
	file_extensions_filters_v1_http_ext_authz_ext_authz_proto_rawDescOnce sync.Once
	file_extensions_filters_v1_http_ext_authz_ext_authz_proto_rawDescData []byte
)

func file_extensions_filters_v1_http_ext_authz_ext_authz_proto_rawDescGZIP() []byte {
	file_extensions_filters_v1_http_ext_authz_ext_authz_proto_rawDescOnce.Do(func() {
		file_extensions_filters_v1_http_ext_authz_ext_authz_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_extensions_filters_v1_http_ext_authz_ext_authz_proto_rawDesc), len(file_extensions_filters_v1_http_ext_authz_ext_authz_proto_rawDesc)))
	})
	return file_extensions_filters_v1_http_ext_authz_ext_authz_proto_rawDescData
}

var file_extensions_filters_v1_http_ext_authz_ext_authz_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_extensions_filters_v1_http_ext_authz_ext_authz_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_extensions_filters_v1_http_ext_authz_ext_authz_proto_goTypes = []any{
	(ExtAuthz_Protocol)(0),      // 0: extensions.filters.http.ext_authz.v1.ExtAuthz.Protocol
	(*ExtAuthz)(nil),            // 1: extensions.filters.http.ext_authz.v1.ExtAuthz
	(*durationpb.Duration)(nil), // 2: google.protobuf.Duration
	(*rbac.Rule)(nil),           // 3: extensions.filters.http.rbac.v1.Rule
}
var file_extensions_filters_v1_http_ext_authz_ext_authz_proto_depIdxs = []int32{
	0, // 0: extensions.filters.http.ext_authz.v1.ExtAuthz.protocol:type_name -> extensions.filters.http.ext_authz.v1.ExtAuthz.Protocol
	2, // 1: extensions.filters.http.ext_authz.v1.ExtAuthz.timeout:type_name -> google.protobuf.Duration
	3, // 2: extensions.filters.http.ext_authz.v1.ExtAuthz.rules:type_name -> extensions.filters.http.rbac.v1.Rule
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_extensions_filters_v1_http_ext_authz_ext_authz_proto_init() }
func file_extensions_filters_v1_http_ext_authz_ext_authz_proto_init() {
	if File_extensions_filters_v1_http_ext_authz_ext_authz_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_extensions_filters_v1_http_ext_authz_ext_authz_proto_rawDesc), len(file_extensions_filters_v1_http_ext_authz_ext_authz_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_extensions_filters_v1_http_ext_authz_ext_authz_proto_goTypes,
		DependencyIndexes: file_extensions_filters_v1_http_ext_authz_ext_authz_proto_depIdxs,
		EnumInfos:         file_extensions_filters_v1_http_ext_authz_ext_authz_proto_enumTypes,
		MessageInfos:      file_extensions_filters_v1_http_ext_authz_ext_authz_proto_msgTypes,
	}.Build()
	File_extensions_filters_v1_http_ext_authz_ext_authz_proto = out.File
	file_extensions_filters_v1_http_ext_authz_ext_authz_proto_goTypes = nil
	file_extensions_filters_v1_http_ext_authz_ext_authz_proto_depIdxs = nil
}
